DROP PROCEDURE IF EXISTS procedure2;
GO
CREATE PROCEDURE procedure2
	@NUMBER INT = NULL OUTPUT
AS
	SET @NUMBER = (SELECT COUNT(DISTINCT(Id_Student))
					FROM studenti_reusita
					WHERE Nota < 5 OR Nota IS NULL)
BEGIN
	SELECT @NUMBER AS NUMBER_STUD
END
GO
EXECUTE procedure2;